@startuml

package "Concept model" #LightGreen {

    rectangle "Car makers" #Cyan {
    component "Automotive embedded system" as CAR_SYSTEM
    package "Internal sub-systems" #LightBlue {
        () "Brake system" as ECU_BS #LightGreen
        () "Fuel injector" as ECU_FI #LightGreen
        () "Engine management" as ECU_EM #LightGreen
}

CAR_SYSTEM .-> ECU_BS
CAR_SYSTEM .-> ECU_FI
CAR_SYSTEM .-> ECU_EM

ECU_FI <.left. ECU_EM #Blue
ECU_BS <.right. ECU_EM #Blue

 note left of CAR_SYSTEM {
     Intimate knowledge
     of all sub-systems.
}

}

}


@enduml
