# Introduction and abstract

### Presenting myself first

#### Jean-Baptiste Laurent

* 1 year teaching
* 3 years in research, static analysis
* 5 years in cyber-security
* 10 years in software development

#### Current status

* LR-Technology consultant, working for Faurecia
  * First, 6 months on the RAPIDE platform [^RAPIDE]
  * Now, exclusively working on the following research topic

### Involved Parties

#### RICHEFEU Julien
  * Faurecia Clarion Electonics, Platform Software Manager
  * PhD Director

#### MENSUEZ Bruno
  * ENSTA Paris-Tech, Teacher
  * PhD Co-Director

### Objective of the presentation

* **Presenting**
  * The **new project** content
  * Who is involved
  * The work I will brought in
* **Precising**
  * How this project could **impact** you in the long run
* Get the time to **exchange** on this


<!--

### Let's make this simple

- This presentation will explain:
  * who will do what,
  * why,
  * how,
  * with whom when,
  * the role each will fill
  * and the benefits in the long run.
- We are all mostly busy, so let's only present the important bit of each
- I will hand a recap at the end.


### The research in itself

* Analyzing the flaws and needs of modern cars embedded systems
* Designing a new architecture to build upon
* Experimentation and prototyping

-->


### Definitions and wording

#### EN -> FR
* **ECU**: Unité de controle
* **Socket suppliers**: Fournisseur de micro processeur
* **OEMs**: Les assembleurs
* **Car maker**: Le fabricant
* **The model**: L'ensemble de l'architecture, du microprocesseur à l'application haut niveau.

[^RAPIDE]: Generic software platform for car embedded systems

<!--

TODO: Write a private FAQ and prepare the answers

-->
